import os
currentdir=os.getcwd()
# changeddir=os.chdir('/Users/liucong/Desktop/115010019')#change the directory
file1=open('TOEFL Vocabulary.txt','w')
file1.write(' '*10+'TOEFL Vocabulary(Right-To-Left)Generated by Python'+'\n')
file1.write(' '*20+'Name:'+' '*10+'Student ID:'+'\n')
file2=open('TOEFL Vocabulary(updated).txt','r')
lines=file2.readlines()
file2.close()
list1=[]
listn=[]
n=0
for element in lines:
    if 'Synonym' in element:#find synonym
        a=element.find(':')
        b=element.find(',')
        synonymwords=element[a+1:]
        Synonym=synonymwords.split(',')
        list1.append(Synonym)
    else:
        list1.append('no')
    if 'Antonym' in element:#find antonym
        c=element.find(':')
        d=element.find(',')
        antonymwords=element[c+1:]
        Antonym=antonymwords.split(',')
        list1.append(Antonym)
    else:
        list1.append('no')
    # else:#count words,find e.g and meanings
        n=n+1
        m=element.find(':')
        n=element.find('-')
        word=str(str(n)+'.'+' '*3+element[:m])
        listn.append(word)
        meanings=element[m+1:n]
        listn.append(meanings)
        example=element[n+1:]
        listn.append(example)
def main(n):#to write the information in a fomat
    file1.write(n[0]+'\n')
    file1.write(' '*5+n[1]+'\n')
    file1.write(' '*5+'E.g.:'+n[2]+'\n')
    if list1[3][0]!='no':
        file1.write(' '*5+'Synonym:\n')
        for synonym in list1[3][1:]:
            file1.write(' '*8+synonym+'\n')
        if list1[4][0]!='no':
            file1.write(' '*5+'Antonym:\n')
            for antonym in list1[4][1:]:
                file1.write(' '*8+antonym+'\n')
    else:
        file1,write(' '*8+'Antonym:'+'\n')
        for antonym in n[3][1:]:
            file1.write(' '*8+antonym+'\n')

for n in listn:
    main(n)
file2.close()






